---

- name: Create AWS VPC
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Create VPC  
      ec2_vpc_net:
       name: my-vpc
       region: eu-west-1
       state: present
       cidr_block: 10.0.5.0/24
      register: id


    - name: Set fact VPC ID
      set_stats:
       data:
        vpc_id: "{{ register.stdout }}"

