---

- name: Create AWS Subnet
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Create AWS subnet for testing purposes 
      ec2_vpc_subnet:
       region: eu-west-1
       state: present
       vpc_id: "{{ vpc_id }}"
       cidr: 10.0.5.0/25
       resource_tags:
         Name: ansible-training-javier
      register: subnet_id
