---

- name: Launch AWS Instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    keypair: 
    instance_type: m1.small
    security_group: 
    image: 
  
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-29e63245
         assign_public_ip: yes
      register: ec2