---

- name: Create instances ("{{ instances }}")
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    #service_account_email: XXXXXX
    # credentials_file: /path/xxxx .json
    project_id: awx-javier-001
    #machine_type: n1-standard-1
    #image: centos-7

  tasks:

    - name: create and start the instance
      gce:
        instance_names: app
        # zone: "{{ zone }}"
        machine_type: f1-micro
        image: centos-7
        state: present
        disk_size: 15
        tags: http
        #metadata: "{{ instance_metadata }}"
        network: my-network
        subnetwork: public-subnet
        #external_ip: "{{ app_eip.address }}"
        service_account_email: "{{ service_account_email }}"
        #credentials_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
        #project_id: "{{ project_id }}"
      tags:
        - recipe2