---

- name: Create Servicenow indicent
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Create an incident
      snow_record:
       username: "{{ service_now_username }}"
       password: "{{ service_now_password }}"
       instance: "{{ service_now_instance }}"
       state: present
       data:
         short_description: "This is a test incident opened by Javier"
         severity: 2
         priority: 1
      register: new_incident

